### ISSUE TITLE
Prośba o dodanie nowych serwisów ??

### ISSUE THREAD

**Issue by eko5** [kapeer/Serialnet.bundle#1]
Witaj bawię się ostanio plexem i tak sprawdzam wtyczki jakie są dostępne i natknełem się na twoje dodatki które są już dość stare , czy istniej abyś dodał jakieś nowe np : ipla , tvn , iitv.pl , alltube.tv ,efilmy.tv , cda-x.pl .

Po za tym znasz może jakieś nowe pluginy polskie w sieci do plexa ??

Dzięki za odpowiedż .

**Comment by kapeer** [comment]
Na razie nie mam planów na dodanie nowych wtyczek, głównie dlatego że mieszkam za granicą i duża część serwisów jest zablokowana (czytaj, nie mam jak przetestować). Zawartość z ipli, tvn in iitv.pl w większości jest dostępna za pomocą wtyczki Serialnet.

Z tego co wiem, to nie ma niestety innej osoby pracującej nad wtyczkami, dlatego zachęcam do nauki programowania i "zabawy" z Plexem ;)

**Comment by adamibeata** [comment]
https://cda-tv.pl
